/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    teamMembers: TeamMember;
    categories: Category;
    locations: Location;
    productCategories: ProductCategory;
    products: Product;
    projects: Project;
    formSubmissions: FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    teamMembers: TeamMembersSelect<false> | TeamMembersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    formSubmissions: FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
    about: About;
    locationsIndex: LocationsIndex;
    productsIndex: ProductsIndex;
    projectsIndex: ProjectsIndex;
    contact: Contact;
    privacyPolicy: PrivacyPolicy;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    locationsIndex: LocationsIndexSelect<false> | LocationsIndexSelect<true>;
    productsIndex: ProductsIndexSelect<false> | ProductsIndexSelect<true>;
    projectsIndex: ProjectsIndexSelect<false> | ProjectsIndexSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    privacyPolicy: PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
  };
  locale: 'de' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers".
 */
export interface TeamMember {
  id: string;
  photo?: (string | null) | Media;
  name: string;
  department?: string | null;
  phone?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title?: string | null;
  category: string | ProductCategory;
  headline: string;
  videoId: string;
  paragraph1: string;
  image1: string | Media;
  paragraph2?: string | null;
  paragraph3?: string | null;
  image2?: (string | null) | Media;
  buttonText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name: string;
  thumbnail: string | Media;
  address?: string | null;
  phone?: string | null;
  time?: string | null;
  headline: string;
  country: string;
  paragraph1?: string | null;
  paragraph2?: string | null;
  paragraph3?: string | null;
  featuredImage: string | Media;
  managers?:
    | {
        name?: string | null;
        position?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: (string | Media)[];
        id?: string | null;
      }[]
    | null;
  teamImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  scientificName?: string | null;
  category: string | ProductCategory;
  thumbnail: string | Media;
  thumbnailColor: string;
  gallery: {
    image: (string | Media)[];
  };
  details?: {
    height?: string | null;
    diameter?: string | null;
    hardiness?: string | null;
    light?: string | null;
  };
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  thumbnail: string | Media;
  cardTitle: string;
  tag: string;
  location?: string | null;
  paragraph1?: string | null;
  paragraph2?: string | null;
  gallery: {
    images: (string | Media)[];
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions".
 */
export interface FormSubmission {
  id: string;
  fullName: string;
  email: string;
  phone?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'teamMembers';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: string | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'formSubmissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  photo?: T;
  name?: T;
  department?: T;
  phone?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  headline?: T;
  videoId?: T;
  paragraph1?: T;
  image1?: T;
  paragraph2?: T;
  paragraph3?: T;
  image2?: T;
  buttonText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  thumbnail?: T;
  address?: T;
  phone?: T;
  time?: T;
  headline?: T;
  country?: T;
  paragraph1?: T;
  paragraph2?: T;
  paragraph3?: T;
  featuredImage?: T;
  managers?:
    | T
    | {
        name?: T;
        position?: T;
        image?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  teamImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  scientificName?: T;
  category?: T;
  thumbnail?: T;
  thumbnailColor?: T;
  gallery?:
    | T
    | {
        image?: T;
      };
  details?:
    | T
    | {
        height?: T;
        diameter?: T;
        hardiness?: T;
        light?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  thumbnail?: T;
  cardTitle?: T;
  tag?: T;
  location?: T;
  paragraph1?: T;
  paragraph2?: T;
  gallery?:
    | T
    | {
        images?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  sections?:
    | (
        | {
            headline: string;
            subtitle?: string | null;
            slides?:
              | {
                  desktopImage: (string | Media)[];
                  mobileImage?: (string | Media)[] | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            tagline?: string | null;
            headline: string;
            paragraph1: string;
            paragraph2?: string | null;
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            tagline?: string | null;
            headline: string;
            paragraph?: string | null;
            cards?:
              | {
                  image: string | Media;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            tagline?: string | null;
            headline: string;
            cards?:
              | {
                  headline: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            tagline?: string | null;
            headline: string;
            thumbnail: string | Media;
            youtubeId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            tagline?: string | null;
            headline: string;
            items?:
              | {
                  photo?: (string | null) | Media;
                  name: string;
                  position?: string | null;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  sections?:
    | (
        | {
            tagline?: string | null;
            headline: string;
            paragraph: string;
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutIntro';
          }
        | {
            story: {
              tagline?: string | null;
              headline: string;
              paragraph: string;
            };
            ceo: {
              photo: string | Media;
              name: string;
              position?: string | null;
            };
            missionVision?: {
              cards?:
                | {
                    name: string;
                    text: string;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutCombined';
          }
        | {
            tagline?: string | null;
            headline: string;
            members?: (string | TeamMember)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamSection';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locationsIndex".
 */
export interface LocationsIndex {
  id: string;
  sections?:
    | {
        tagline?: string | null;
        headline: string;
        paragraph1: string;
        paragraph2?: string | null;
        image: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'locationsIntro';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productsIndex".
 */
export interface ProductsIndex {
  id: string;
  sections?:
    | {
        tagline?: string | null;
        headline: string;
        paragraph?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productsIntro';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectsIndex".
 */
export interface ProjectsIndex {
  id: string;
  sections?:
    | {
        tagline?: string | null;
        headline: string;
        paragraph?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectsIntro';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  address?: {
    line1?: string | null;
    line2?: string | null;
    line3?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedIn?: string | null;
    youtube?: string | null;
  };
  formSettings: {
    toEmail: string;
    subjectPrefix?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyPolicy".
 */
export interface PrivacyPolicy {
  id: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subtitle?: T;
              slides?:
                | T
                | {
                    desktopImage?: T;
                    mobileImage?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              tagline?: T;
              headline?: T;
              paragraph1?: T;
              paragraph2?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              tagline?: T;
              headline?: T;
              paragraph?: T;
              cards?:
                | T
                | {
                    image?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              tagline?: T;
              headline?: T;
              cards?:
                | T
                | {
                    headline?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              tagline?: T;
              headline?: T;
              thumbnail?: T;
              youtubeId?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              tagline?: T;
              headline?: T;
              items?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    position?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        aboutIntro?:
          | T
          | {
              tagline?: T;
              headline?: T;
              paragraph?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        aboutCombined?:
          | T
          | {
              story?:
                | T
                | {
                    tagline?: T;
                    headline?: T;
                    paragraph?: T;
                  };
              ceo?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    position?: T;
                  };
              missionVision?:
                | T
                | {
                    cards?:
                      | T
                      | {
                          name?: T;
                          text?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        teamSection?:
          | T
          | {
              tagline?: T;
              headline?: T;
              members?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locationsIndex_select".
 */
export interface LocationsIndexSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        locationsIntro?:
          | T
          | {
              tagline?: T;
              headline?: T;
              paragraph1?: T;
              paragraph2?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productsIndex_select".
 */
export interface ProductsIndexSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        productsIntro?:
          | T
          | {
              tagline?: T;
              headline?: T;
              paragraph?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectsIndex_select".
 */
export interface ProjectsIndexSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        projectsIntro?:
          | T
          | {
              tagline?: T;
              headline?: T;
              paragraph?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        line3?: T;
        phone?: T;
        email?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedIn?: T;
        youtube?: T;
      };
  formSettings?:
    | T
    | {
        toEmail?: T;
        subjectPrefix?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyPolicy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}